version: "3.9"

services:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: foo-db
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo

  node:
    container_name: nodejs
    image: node
    user: "node"
    working_dir: /var/www
    volumes:
      - ./www:/var/www

  php:
    container_name: php
    depends_on:
      - mysql
      - node
    build: ./images/php
    volumes:
      - ./www:/var/www:rw

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./templates:/etc/nginx/templates
      - ./www:/var/www

  adminer:
    container_name: adminer
    depends_on:
      - mysql
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql: {}

# https://hub.docker.com/_/php?tab=description&page=1&ordering=last_updated
# https://miac.volmed.org.ru/wiki/index.php/Docker-compose_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0_%D0%B4%D0%BB%D1%8F_%D1%81%D0%B0%D0%B9%D1%82%D0%B0_NGINX_%2B_MYSQL_%2B_PHP-FPM
# https://www.cs-cart.ru/docs/4.2.x/manager/install/vps/nginx/